1.1-v.4
Team-Maksym/frontend pull request #40
Opened 2023-03-25 16:33 UTC by AnnaSukharieva

2023-03-25 17:03 UTC, Scaliariy requested changes

2023-03-25 17:06 UTC, Scaliariy reviewed
мне кажется это должно быть не здесь, может лучше в компоненте TalentList ?

2023-03-25 17:07 UTC, Scaliariy commented on src/components/App.jsx
> +
мне кажется это должно быть не здесь, может лучше в компоненте TalentList ?

2023-03-25 22:22 UTC, AnnaSukharieva commented on src/components/App.jsx
> +
чекай 5 версию, исправила

2023-03-26 09:34 UTC, ShirayDan commented on src/components/TalentList/TalentList.jsx
> +
два пробела

2023-03-26 09:34 UTC, ShirayDan commented on src/components/TalentList/TalentList.jsx
> +
пробел

2023-03-26 09:34 UTC, ShirayDan commented on src/components/TalentList/TalentList.jsx
> +
пробел

2023-03-26 09:34 UTC, ShirayDan commented on src/service/ProfileService.js
> +
пробел

2023-03-26 09:45 UTC, kpodus approved these changes

2023-03-26 20:09 UTC, merged